### ISSUE TITLE
Cannot run predictor.py due to missing dependencies

### ISSUE THREAD

**Issue by jfsantos** [biboamy/TVSM-dataset#5]
Following the instructions from README.md and installing all dependencies from `requirements.txt` I still get this error when trying to run the script to predict labels:

```
python3 training_code/predictor.py
Traceback (most recent call last):
  File "training_code/predictor.py", line 8, in <module>
    from SM_detector import SM_detector
  File "/home/jsantos/src/TVSM-dataset/training_code/SM_detector.py", line 10, in <module>
    from utils.creator import dataset_creator, model_creator, preprocess_creator
  File "/home/jsantos/src/TVSM-dataset/training_code/utils/creator.py", line 1, in <module>
    from dataloader import avaspeech_dataset, muspeak_dataset, netflix_dataset, klaus_dataset, netflix_eval_dataset, netflix_whole_dataset, bmat_dataset
  File "/home/jsantos/src/TVSM-dataset/training_code/dataloader/avaspeech_dataset.py", line 10, in <module>
    from dataset_module import Dataset
```

Where does `dataset_module` come from? Is it a missing file in this repo or is it available in another repo?

**Comment by biboamy** [comment]
@jfsantos  Thanks for raising this issue! I think I forget to mention in the README, but `predictor.py` should be run under `training_code` directory. So if you `cd training_code` then run `python3 predictor.py`, this error should disappear. Let me know if this works. I will include this reminder in the README as well.
